name: Clippy

on: [push, pull_request, workflow_dispatch]

jobs:
  clippy-portable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Rust
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  clippy-sse:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Ctarget-feature=+sse4.2"
      RUSTDOCFLAGS: "-Ctarget-feature=+sse4.2"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Rust
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  clippy-crc:
      runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Ctarget-feature=+crc"
      RUSTDOCFLAGS: "-Ctarget-feature=+crc"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Rust
      run: rustup component add clippy
    - name: Run Clippy
      run: cargo clippy --target=aarch64-unknown-linux-gnu --all-features -- -D warnings